"use client";
import { useState } from "react";
import { FileDown, Printer, Users, CheckCircle2, AlertCircle, MapPin, ClipboardCheck } from "lucide-react";
import Image from "next/image";
import { useWorkspace } from "./context";
import { TripSelect } from "./ui";
export function Attendance(){
 const {state,run,busy}=useWorkspace();const [tripId,setTripId]=useState(state.trips[0]?.id??"");
 const participants=state.participants.filter(p=>p.tripId===tripId&&p.status==="active");const trip=state.trips.find(t=>t.id===tripId);const incomplete=participants.filter(p=>!p.name.trim()||!p.meetingPoint.trim()).length;
 function exportAttendance(){void run(async()=>{
  if(incomplete)throw new Error("Fill in every participant's name and meeting point before printing.");
  
  const response=await fetch("/api/attendance/export",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tripId})});if(!response.ok){const e=await response.json();throw new Error(e.error);}const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`attendance-${tripId}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
 });}
 return <div className="attendance-layout"><aside className="attendance-controls"><section className="td-panel"><div className="panel-heading"><h2>Prepare attendance list</h2><ClipboardCheck size={18}/></div><TripSelect value={tripId} onChange={setTripId} all="Select trip"/><div className="attendance-fact"><Users size={16}/><span>Total active participants</span><strong>{participants.length}</strong></div><div className="attendance-fact"><MapPin size={16}/><span>Meeting points filled</span><strong>{participants.length-incomplete}</strong></div><div className="attendance-fact"><CheckCircle2 size={16}/><span>Status coverage</span><strong>All</strong></div><div className="attendance-info"><AlertCircle size={16}/><p>Fully paid, deposit, and unpaid participants are all included. Nobody is left out.</p></div><button className="td-button w-full" disabled={busy||!participants.length} onClick={exportAttendance}><FileDown size={15}/>{"Download attendance PDF"}</button><p className="paper-settings">A4 portrait · 6 columns · {participants.length} participants</p></section><div className="guide-note"><Printer size={22}/><h3>Ready for the guide.</h3><p>The Basecamp, Meal, and Return columns are left blank for on-site checks.</p></div></aside>
 <section className="document-workspace"><div className="document-toolbar"><span><span className="status-dot"/> Attendance preview</span><span>100% <span className="toolbar-divider">|</span> A4</span></div><div className="paper-scroll"><article className="paper-preview"><div className="paper-header"><Image src="/brand/rimbaloka-logo.jpeg" alt="Rimbaloka Trip" width={64} height={64}/><div><p>RIMBALOKA TRIP</p><h2>PARTICIPANT ATTENDANCE</h2><h3>{trip?.title??"Select a trip"}</h3><small>{trip?new Date(`${trip.departureDate}T12:00:00`).toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"}):""}</small></div></div><div className="paper-rule"/><div className="paper-meta"><span>Total: <strong>{participants.length} participants</strong></span><span>{"DOKUMEN OPERASIONAL"}</span></div><table className="attendance-paper-table"><thead><tr>{["NO","NAME","MEETING POINT","BASECAMP","MEAL","RETURN"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{participants.map((p,i)=><tr key={p.id}><td>{i+1}</td><td>{p.name}</td><td>{p.meetingPoint||"Missing"}</td><td></td><td></td><td></td></tr>)}</tbody></table>{!participants.length&&<p className="empty-note py-10 text-center">Select a trip with participants to see a preview.</p>}<div className="paper-footer"><span>Rimbaloka Trip · Every journey, well managed.</span><span>TripDash</span></div></article></div></section></div>;
}
