"use client";
import { useState } from "react";
import { FileDown, Printer, Users, CheckCircle2, AlertCircle, MapPin, ClipboardCheck } from "lucide-react";
import Image from "next/image";
import { useWorkspace } from "./context";
import { TripSelect } from "./ui";
import { renderAttendanceTemplate } from "@/lib/pdf/attendance-template";
export function Attendance(){
 const {state,run,busy,prototype,revision}=useWorkspace();const [tripId,setTripId]=useState(state.trips[0]?.id??"");
 const participants=state.participants.filter(p=>p.tripId===tripId&&p.status==="active");const trip=state.trips.find(t=>t.id===tripId);const incomplete=participants.filter(p=>!p.name.trim()||!p.meetingPoint.trim()).length;
 function exportAttendance(){void run(async()=>{
  if(incomplete)throw new Error("Lengkapi nama dan MEPO seluruh peserta sebelum mencetak.");
  if(prototype){const popup=window.open("","_blank","width=900,height=700");if(!popup)throw new Error("Izinkan pop-up untuk membuka cetak PDF.");const html=renderAttendanceTemplate({tripId,title:`Absensi ${trip?.title??"Trip"} — SIMULASI`,organizer:"Rimbaloka Trip",version:revision,snapshotAt:new Date()},participants.map(p=>({id:p.id,bookingId:p.bookingId,name:p.name,meetingPoint:p.meetingPoint,status:p.status})));popup.document.write(html);popup.document.close();popup.focus();setTimeout(()=>popup.print(),500);return;}
  const response=await fetch("/api/attendance/export",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tripId})});if(!response.ok){const e=await response.json();throw new Error(e.error);}const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`absensi-${tripId}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
 });}
 return <div className="attendance-layout"><aside className="attendance-controls"><section className="td-panel"><div className="panel-heading"><h2>Siapkan daftar hadir</h2><ClipboardCheck size={18}/></div><TripSelect value={tripId} onChange={setTripId} all="Pilih trip"/><div className="attendance-fact"><Users size={16}/><span>Total peserta aktif</span><strong>{participants.length}</strong></div><div className="attendance-fact"><MapPin size={16}/><span>Meeting point terisi</span><strong>{participants.length-incomplete}</strong></div><div className="attendance-fact"><CheckCircle2 size={16}/><span>Cakupan status</span><strong>Semua</strong></div><div className="attendance-info"><AlertCircle size={16}/><p>Peserta lunas, DP, dan belum bayar tetap masuk absensi. Tidak ada peserta yang terlewat.</p></div><button className="td-button w-full" disabled={busy||!participants.length} onClick={exportAttendance}><FileDown size={15}/>{prototype?"Cetak / simpan PDF":"Unduh PDF absensi"}</button><p className="paper-settings">A4 portrait · 6 kolom · {participants.length} peserta</p>{prototype&&<p className="empty-note">Pilih “Simpan sebagai PDF” pada dialog cetak browser.</p>}</section><div className="guide-note"><Printer size={22}/><h3>Siap dibawa guide.</h3><p>Kolom Basecamp, Makan, dan Pulang sengaja kosong untuk pengecekan di lapangan.</p></div></aside>
 <section className="document-workspace"><div className="document-toolbar"><span><span className="status-dot"/> Pratinjau absensi</span><span>100% <span className="toolbar-divider">|</span> A4</span></div><div className="paper-scroll"><article className="paper-preview"><div className="paper-header"><Image src="/brand/rimbaloka-logo.jpeg" alt="Rimbaloka Trip" width={64} height={64}/><div><p>RIMBALOKA TRIP</p><h2>DAFTAR HADIR PESERTA</h2><h3>{trip?.title??"Pilih perjalanan"}</h3><small>{trip?new Date(`${trip.departureDate}T12:00:00`).toLocaleDateString("id-ID",{day:"numeric",month:"long",year:"numeric"}):""}</small></div></div><div className="paper-rule"/><div className="paper-meta"><span>Total: <strong>{participants.length} peserta</strong></span><span>{prototype?"DOKUMEN SIMULASI":"DOKUMEN OPERASIONAL"}</span></div><table className="attendance-paper-table"><thead><tr>{["NO","NAMA","MEPO","BASECAMP","MAKAN","PULANG"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{participants.map((p,i)=><tr key={p.id}><td>{i+1}</td><td>{p.name}</td><td>{p.meetingPoint||"Perlu dilengkapi"}</td><td></td><td></td><td></td></tr>)}</tbody></table>{!participants.length&&<p className="empty-note py-10 text-center">Pilih trip dengan peserta untuk melihat pratinjau.</p>}<div className="paper-footer"><span>Rimbaloka Trip · Every journey, well managed.</span><span>TripDash</span></div></article></div></section></div>;
}
