"use client";
import { useState } from "react";
import { ArrowDownLeft, ArrowUpRight, Plus, Wallet, TrendingUp, CalendarDays, Receipt, Download } from "lucide-react";
import { formatRupiah } from "@/lib/money";
import { periodBounds } from "@/lib/workspace/period";
import { useWorkspace } from "./context";
import { Field, Form, number, Select, Submit, text, TripSelect, Modal } from "./ui";
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
export function Finance(){
 const {state,mutate,prototype}=useWorkspace();const [tripId,setTripId]=useState("");const [expenseTrip,setExpenseTrip]=useState("");const [period,setPeriod]=useState("month");const [reference,setReference]=useState(prototype?"2026-09-11":today);const [creating,setCreating]=useState(false);const [direction,setDirection]=useState("");
 const [start,end]=periodBounds(period,reference);const entries=state.cash.filter(c=>(!tripId||c.tripId===tripId)&&Date.parse(c.occurredAt)>=start&&Date.parse(c.occurredAt)<end).sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt));
 const income=entries.filter(e=>e.direction==="in").reduce((s,e)=>s+e.amount,0);const expense=entries.filter(e=>e.direction==="out").reduce((s,e)=>s+e.amount,0);const visible=entries.filter(e=>!direction||e.direction===direction);
 const categories=[...new Set(entries.filter(e=>e.direction==="out").map(e=>e.category))].map(category=>({category,amount:entries.filter(e=>e.direction==="out"&&e.category===category).reduce((s,e)=>s+e.amount,0)}));
 function exportCsv(){const escape=(s:string)=>'"'+(/^[=+@-]/.test(s)?"'":"")+s.replace(/"/g,'""')+'"';const csv="\ufeffTanggal WIB,Trip,Kategori,Keterangan,Masuk,Keluar\n"+visible.map(e=>[new Date(e.occurredAt).toLocaleString("id-ID",{timeZone:"Asia/Jakarta"}),state.trips.find(t=>t.id===e.tripId)?.title??"Umum bisnis",e.category,e.description,e.direction==="in"?String(e.amount):"0",e.direction==="out"?String(e.amount):"0"].map(escape).join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=prototype?"keuangan-simulasi.csv":"keuangan-trip.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="section-stack"><div className="finance-filters"><TripSelect value={tripId} onChange={setTripId}/><Select label="Periode" value={period} onChange={setPeriod}><option value="all">Semua waktu</option><option value="week">Mingguan</option><option value="month">Bulanan</option><option value="year">Tahunan</option></Select><Field label="Tanggal acuan (WIB)" type="date" value={reference} required onChange={e=>e.target.value&&setReference(e.target.value)}/><button className="td-button" onClick={()=>setCreating(true)}><Plus size={15}/> Catat pengeluaran</button></div>
 <div className="finance-summary">{[{label:"Pemasukan terverifikasi",value:income,icon:ArrowDownLeft,note:"Pembayaran peserta & DP",type:"income"},{label:"Total pengeluaran",value:expense,icon:ArrowUpRight,note:"Biaya operasional tercatat",type:"expense"},{label:"Arus kas bersih",value:income-expense,icon:Wallet,note:"Pemasukan dikurangi pengeluaran",type:"net"}].map(s=><article className={`finance-stat ${s.type}`} key={s.label}><span className="finance-stat-icon"><s.icon size={20}/></span><span>{s.label}</span><strong>{formatRupiah(s.value)}</strong><small>{s.note}</small></article>)}</div>
 <div className="finance-detail-grid"><section className="td-panel"><div className="panel-heading"><h2>Komposisi arus kas</h2><span className="badge gray">Sesuai filter</span></div><div className="cash-composition"><div><span>Uang masuk</span><strong>{formatRupiah(income)}</strong></div><div className="composition-track"><span style={{width:`${income+expense?income/(income+expense)*100:0}%`}}/></div><div><span>Uang keluar</span><strong>{formatRupiah(expense)}</strong></div></div><p className="empty-note">Kas masuk dicatat sesuai timestamp pendaftaran setelah transfer diverifikasi. Saldo awal rekening belum ditetapkan.</p></section><section className="td-panel"><div className="panel-heading"><h2>Pengeluaran per kategori</h2><Receipt size={16}/></div>{categories.map((c,i)=><div className="category-breakdown" key={c.category}><i style={{background:["#6b8a61","#a5b18b","#d0c29a"][i%3]}}/><span>{c.category}</span><strong>{formatRupiah(c.amount)}</strong></div>)}{!categories.length&&<p className="empty-note">Belum ada pengeluaran pada periode ini.</p>}</section></div>
 <section className="td-panel"><div className="panel-heading"><div><h2>Riwayat transaksi</h2><p className="panel-subtitle">Setiap pemasukan dan pengeluaran, tercatat dengan jelas.</p></div><button className="td-secondary" disabled={!visible.length} onClick={exportCsv}><Download size={13}/> Ekspor CSV</button></div><div className="status-tabs" role="group" aria-label="Jenis transaksi">{[["","Semua transaksi"],["in","Pemasukan"],["out","Pengeluaran"]].map(([v,l])=><button key={v} className={direction===v?"active":""} aria-pressed={direction===v} onClick={()=>setDirection(v)}>{l}<span>{entries.filter(e=>!v||e.direction===v).length}</span></button>)}</div><div className="table-wrap mt-5"><table className="td-table"><thead><tr><th>Transaksi</th><th>Trip</th><th>Tanggal WIB</th><th>Kategori</th><th>Nominal</th></tr></thead><tbody>{visible.map(e=><tr key={e.id}><td><div className="transaction-name"><span className={`transaction-icon ${e.direction}`}>{e.direction==="in"?<ArrowDownLeft size={16}/>:<ArrowUpRight size={16}/>}</span><div><strong>{e.description}</strong><small>{e.direction==="in"?"Pemasukan terverifikasi":"Pengeluaran operasional"}</small></div></div></td><td>{state.trips.find(t=>t.id===e.tripId)?.title??"Umum bisnis"}</td><td>{new Date(e.occurredAt).toLocaleDateString("id-ID",{day:"numeric",month:"short",year:"numeric",timeZone:"Asia/Jakarta"})}<small className="block mt-1">{e.dateSource==="registration"?"Timestamp pendaftaran":"Tanggal pengeluaran"}</small></td><td><span className="category-tag">{e.category}</span></td><td className={`money-cell ${e.direction==="in"?"cash-in":"cash-out"}`}>{e.direction==="in"?"+":"−"} {formatRupiah(e.amount)}</td></tr>)}</tbody></table>{!visible.length&&<div className="empty-state"><Receipt size={27}/><h3>Belum ada transaksi</h3><p>Ubah filter atau tambahkan pengeluaran pertama Anda.</p></div>}</div><div className="table-foot"><span>{visible.length} transaksi pada filter ini</span><span>Zona waktu Asia/Jakarta</span></div></section>
 {creating&&<Modal title="Catat pengeluaran" onClose={()=>setCreating(false)}><TripSelect value={expenseTrip} onChange={setExpenseTrip} all="Umum bisnis"/><Form onSave={async d=>{await mutate({action:"expense.create",tripId:expenseTrip,amount:number(d,"amount"),date:text(d,"date"),category:text(d,"category"),description:text(d,"description")});setCreating(false);}}><Field label="Nominal pengeluaran (Rp)" name="amount" type="number" min={1} required placeholder="0"/><Field label="Tanggal pengeluaran (WIB)" name="date" type="date" defaultValue={prototype?"2026-09-11":today()} required/><Field label="Kategori" name="category" list="expense-categories" required placeholder="Pilih atau tulis kategori baru"/><datalist id="expense-categories">{[...new Set(["Transportasi","Konsumsi","Tiket","Sewa alat",...state.cash.filter(e=>e.direction==="out").map(e=>e.category)])].map(c=><option key={c}>{c}</option>)}</datalist><Field label="Keterangan" name="description" required placeholder="Contoh: DP sewa kendaraan"/><Submit><Plus size={14}/> Simpan pengeluaran</Submit></Form></Modal>}
 </div>;
}
