"use client";
import { useState } from "react";
import { Plus, Search, Package, Tent, Flashlight, CloudRain, CookingPot, HeartPulse, Footprints, ArrowUpRight, RotateCcw, SlidersHorizontal, Boxes } from "lucide-react";
import { availableStock, type Inventory as Item } from "@/lib/workspace/types";
import { useWorkspace } from "./context";
import { Field, Form, number, Submit, text, TripSelect, Modal } from "./ui";
const itemIcon=(name:string)=>/tenda/i.test(name)?Tent:/headlamp/i.test(name)?Flashlight:/hujan/i.test(name)?CloudRain:/cooking/i.test(name)?CookingPot:/p3k/i.test(name)?HeartPulse:/trekking/i.test(name)?Footprints:Package;
export function Inventory(){
 const {state,mutate,run,busy}=useWorkspace();const [tripId,setTripId]=useState(state.trips[0]?.id??"");const [search,setSearch]=useState("");const [kind,setKind]=useState("");const [creating,setCreating]=useState(false);const [lending,setLending]=useState<Item|null>(null);const [adjusting,setAdjusting]=useState<Item|null>(null);
 const items=state.inventory.filter(i=>i.name.toLowerCase().includes(search.toLowerCase())&&(!kind||i.kind===kind));
 const total=state.inventory.reduce((s,i)=>s+i.total,0);const available=state.inventory.reduce((s,i)=>s+availableStock(i),0);const damaged=state.inventory.reduce((s,i)=>s+i.damaged,0);
 return <div className="section-stack"><div className="stats-grid participant-stats">{[{label:"Jenis perlengkapan",value:state.inventory.length,icon:Boxes},{label:"Stok tersedia",value:available,icon:Package},{label:"Sedang digunakan",value:total-available-damaged,icon:Tent},{label:"Perlu perawatan",value:damaged,icon:SlidersHorizontal}].map(s=><div key={s.label} className="stat-card"><div className="stat-top"><span>{s.label}</span><span className="stat-icon"><s.icon size={16}/></span></div><div className="stat-value">{s.value}<small> {s.label==="Jenis perlengkapan"?"jenis":"unit"}</small></div></div>)}</div>
 <div className="inventory-toolbar"><div className="status-tabs" role="group" aria-label="Jenis inventaris">{[["","Semua barang"],["operational","Operasional"],["rental","Sewaan"]].map(([v,l])=><button className={kind===v?"active":""} aria-pressed={kind===v} onClick={()=>setKind(v)} key={v}>{l}</button>)}</div><button className="td-button" onClick={()=>setCreating(true)}><Plus size={15}/> Tambah barang</button></div><label className="search-field"><Search size={16}/><input aria-label="Cari barang" placeholder="Cari perlengkapan…" value={search} onChange={e=>setSearch(e.target.value)}/></label>
 <div className="inventory-grid">{items.map(item=>{const Icon=itemIcon(item.name);const available=availableStock(item);const used=item.total-item.damaged-available;return <article className="inventory-card" key={item.id}><div className="inventory-card-top"><span className="inventory-illustration"><Icon size={35} strokeWidth={1.3}/></span><span className={`badge ${available>0?"":"red"}`}>{available>0?"Tersedia":"Stok habis"}</span></div><span className="eyebrow">{item.kind==="rental"?"PERLENGKAPAN SEWA":"BARANG OPERASIONAL"}</span><h2>{item.name}</h2><div className="stock-figures"><div><strong>{available}<small> / {item.total}</small></strong><span>Unit tersedia</span></div><div><span>Digunakan <b>{used}</b></span><span>Rusak <b>{item.damaged}</b></span></div></div><div className="stock-meter"><span style={{width:`${item.total?available/item.total*100:0}%`}}/><i style={{width:`${item.total?used/item.total*100:0}%`}}/></div><div className="inventory-actions"><button className="td-secondary" disabled={!available} onClick={()=>setLending(item)}>Catat barang keluar <ArrowUpRight size={13}/></button><button className="table-icon" aria-label={`Koreksi stok ${item.name}`} onClick={()=>setAdjusting(item)}><SlidersHorizontal size={14}/></button></div>{item.loans.filter(l=>!l.returned).map(l=><div className="active-loan" key={l.id}><span>{state.trips.find(t=>t.id===l.tripId)?.title}<small>{l.quantity} unit dibawa</small></span><button disabled={busy} aria-label={`Kembalikan ${item.name} dari ${state.trips.find(t=>t.id===l.tripId)?.title}`} onClick={()=>void run(()=>mutate({action:"inventory.return",itemId:item.id,loanId:l.id}))}><RotateCcw size={12}/> Kembali</button></div>)}</article>;})}</div>{!items.length&&<div className="empty-state"><Package size={30}/><h3>Belum ada perlengkapan</h3><p>Tambahkan barang atau ubah pencarian Anda.</p></div>}
 {creating&&<Modal title="Tambah perlengkapan" onClose={()=>setCreating(false)}><Form onSave={async d=>{await mutate({action:"inventory.create",name:text(d,"name"),kind:text(d,"kind") as "operational"|"rental",total:number(d,"total")});setCreating(false);}}><Field label="Nama barang" name="name" required placeholder="Contoh: Tenda dome 4 orang"/><label className="form-label">Jenis barang<select name="kind" className="td-input"><option value="operational">Operasional</option><option value="rental">Sewaan</option></select></label><Field label="Jumlah stok total" name="total" type="number" min={0} required/><Submit><Plus size={14}/> Tambah barang</Submit></Form></Modal>}
 {lending&&<Modal title="Catat barang keluar" onClose={()=>setLending(null)}><div className="loan-heading"><Package size={24}/><div><strong>{lending.name}</strong><small>Tersedia {availableStock(lending)} unit</small></div></div><TripSelect value={tripId} onChange={setTripId} all="Pilih trip peminjam"/><Form onSave={async d=>{await mutate({action:"inventory.lend",itemId:lending.id,tripId,quantity:number(d,"quantity")});setLending(null);}}><Field label="Jumlah dibawa / disewakan" name="quantity" type="number" min={1} max={availableStock(lending)} required defaultValue={1}/><Submit>Konfirmasi barang keluar</Submit></Form></Modal>}
 {adjusting&&<Modal title="Koreksi stok barang" onClose={()=>setAdjusting(null)}><p className="empty-note mb-5">{adjusting.name} · Semua perubahan stok dicatat dalam aktivitas.</p><Form onSave={async d=>{await mutate({action:"inventory.adjust",itemId:adjusting.id,total:number(d,"total"),damaged:number(d,"damaged"),reason:text(d,"reason")});setAdjusting(null);}}><Field label="Stok total baru" name="total" type="number" min={0} defaultValue={adjusting.total} required/><Field label="Jumlah barang rusak" name="damaged" type="number" min={0} defaultValue={adjusting.damaged} required/><Field label="Alasan perubahan" name="reason" required placeholder="Contoh: penambahan pembelian barang"/><Submit>Simpan koreksi</Submit></Form></Modal>}
 </div>;
}
