"use client";
import { useState } from "react";
import { Search, SlidersHorizontal, Check, Users, Wallet, Clock3, FileCheck2, ExternalLink, Pencil, ArrowRight, CircleAlert } from "lucide-react";
import { formatRupiah } from "@/lib/money";
import { paidFor, type Person } from "@/lib/workspace/types";
import { useWorkspace } from "./context";
import { Field, Form, number, Panel, Select, Submit, text, TripSelect, Modal } from "./ui";
export function Participants() {
 const {state,mutate,prototype}=useWorkspace();
 const [tripId,setTripId]=useState("");const [search,setSearch]=useState("");const [status,setStatus]=useState("");const [mepo,setMepo]=useState("");const [facility,setFacility]=useState("");const [filters,setFilters]=useState(false);const [page,setPage]=useState(0);const [sort,setSort]=useState("source");
 const [editing,setEditing]=useState<Person|null>(null);const [selected,setSelected]=useState<string[]>([]);const [amount,setAmount]=useState(0);const [proof,setProof]=useState<Person|null>(null);
 const billStatus=(p:Person)=>!p.reviewed?"review":paidFor(state,p.id)>=p.charge?"paid":paidFor(state,p.id)>0?"dp":"unpaid";
 const labels:Record<string,string>={review:"Perlu tinjau",paid:"Lunas",dp:"DP",unpaid:"Belum bayar"};
 const active=state.participants.filter(p=>p.status==="active"&&(!tripId||p.tripId===tripId));
 const filtered=active.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())&&(!status||billStatus(p)===status)&&(!mepo||p.meetingPoint===mepo)&&(!facility||p.facility===facility));
 if(sort==="name")filtered.sort((a,b)=>a.name.localeCompare(b.name,"id"));
 if(sort==="remaining")filtered.sort((a,b)=>(b.charge-paidFor(state,b.id))-(a.charge-paidFor(state,a.id)));
 const currentPage=Math.min(page,Math.max(0,Math.ceil(filtered.length/50)-1));
 const chosen=selected.map(id=>state.participants.find(p=>p.id===id)!).filter(Boolean);
 const remaining=chosen.reduce((s,p)=>s+Math.max(p.charge-paidFor(state,p.id),0),0);
 function choose(ids:string[]){setSelected(ids);setAmount(ids.reduce((s,id)=>{const p=state.participants.find(p=>p.id===id)!;return s+Math.max(p.charge-paidFor(state,id),0);},0));}
 const counters=[{label:"Peserta terdaftar",value:active.length,icon:Users},{label:"Sudah lunas",value:active.filter(p=>billStatus(p)==="paid").length,icon:Check},{label:"Pembayaran DP",value:active.filter(p=>billStatus(p)==="dp").length,icon:Wallet},{label:"Perlu ditindaklanjuti",value:active.filter(p=>["unpaid","review"].includes(billStatus(p))).length,icon:Clock3}];
 return <div className="section-stack"><div className="stats-grid participant-stats">{counters.map(c=><div className="stat-card" key={c.label}><div className="stat-top"><span>{c.label}</span><span className="stat-icon"><c.icon size={16}/></span></div><div className="stat-value">{c.value}<small> orang</small></div></div>)}</div>
 <section className="td-panel participants-panel"><div className="panel-heading"><div><h2>Daftar peserta</h2><p className="panel-subtitle">{new Set(active.map(p=>p.bookingId)).size} respons pendaftaran menjadi {active.length} peserta</p></div><div className="compact-select"><TripSelect value={tripId} onChange={v=>{setTripId(v);setPage(0);}}/></div></div>
 <div className="status-tabs" role="group" aria-label="Filter status pembayaran">{[["","Semua peserta"],["paid","Lunas"],["dp","DP"],["unpaid","Belum bayar"],["review","Perlu tinjau"]].map(([v,l])=><button key={v} aria-pressed={status===v} className={status===v?"active":""} onClick={()=>{setStatus(v);setPage(0);}}>{l}<span>{v?active.filter(p=>billStatus(p)===v).length:active.length}</span></button>)}</div>
 <div className="table-toolbar"><label className="search-field"><Search size={16}/><input aria-label="Cari nama peserta" placeholder="Cari nama peserta…" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label><button className="td-secondary" aria-expanded={filters} onClick={()=>setFilters(!filters)}><SlidersHorizontal size={14}/> Filter</button><div className="sort-select"><Select label="Urutkan" value={sort} onChange={setSort}><option value="source">Urutan pendaftaran</option><option value="name">Nama A–Z</option><option value="remaining">Sisa terbesar</option></Select></div></div>
 {filters&&<div className="filter-expand"><Select label="MEPO" value={mepo} onChange={setMepo}><option value="">Semua MEPO</option>{[...new Set(active.map(p=>p.meetingPoint))].filter(Boolean).map(v=><option key={v}>{v}</option>)}</Select><Select label="Fasilitas" value={facility} onChange={setFacility}><option value="">Semua fasilitas</option><option>Full Transport</option><option>Non Transport</option></Select></div>}
 <div className="table-wrap"><table className="td-table"><thead><tr>{["Peserta","Fasilitas / MEPO","Tagihan","Terbayar","Sisa tagihan","Status","Aksi"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{filtered.slice(currentPage*50,currentPage*50+50).map(p=>{const booking=state.bookings.find(b=>b.id===p.bookingId)!;const paid=paidFor(state,p.id);const group=active.filter(m=>m.tripId===p.tripId&&state.bookings.find(b=>b.id===m.bookingId)?.proof===booking.proof&&paidFor(state,m.id)<m.charge);return <tr key={p.id}><td><div className="overview-table-avatar"><span className="person-avatar">{p.name.split(' ').slice(0,2).map(n=>n[0]).join('')}</span><div><strong>{p.name}</strong><small>{p.raincoats?`+ ${p.raincoats} jas hujan`:p.raincoats===null?"Jas hujan perlu ditinjau":"Tanpa add-on"}</small></div></div>{booking.proof&&<button className="proof-link" onClick={()=>setProof(p)}><FileCheck2 size={11}/> Lihat bukti</button>}</td><td>{p.facility}<small className="block mt-1">{p.meetingPoint||"MEPO belum diisi"}</small></td><td className="money-cell">{formatRupiah(p.charge)}{!p.reviewed&&<small className="block">Sementara</small>}</td><td className="money-cell">{formatRupiah(paid)}</td><td className={`money-cell ${p.charge>paid?"remaining-money":""}`}>{formatRupiah(Math.max(p.charge-paid,0))}</td><td><span className={`badge ${billStatus(p)==="paid"?"":billStatus(p)==="unpaid"?"gray":"amber"}`}>{labels[billStatus(p)]}</span></td><td><div className="row-actions"><button className="table-icon" aria-label={`Tinjau ${p.name}`} onClick={()=>setEditing(p)}><Pencil size={13}/></button>{p.reviewed&&paid<p.charge&&<button className="verify-small" onClick={()=>choose([p.id])}>Verifikasi <ArrowRight size={11}/></button>}{booking.proof&&group.length>1&&<button className="group-small" onClick={()=>choose(group.map(m=>m.id))}><Users size={12}/> Grup {group.length}</button>}</div></td></tr>;})}</tbody></table>{!filtered.length&&<div className="empty-state"><Search size={26}/><h3>Tidak ada peserta yang cocok</h3><p>Coba nama atau filter lain, atau impor respons di menu Trip.</p></div>}</div>
 <div className="table-foot"><span>Menampilkan {Math.min(currentPage*50+1,filtered.length)}–{Math.min((currentPage+1)*50,filtered.length)} dari {filtered.length} peserta</span><div className="pagination"><button disabled={currentPage===0} onClick={()=>setPage(currentPage-1)}>Sebelumnya</button><span>{currentPage+1}</span><button disabled={(currentPage+1)*50>=filtered.length} onClick={()=>setPage(currentPage+1)}>Berikutnya</button></div></div></section>
 {editing&&<Modal title="Tinjau data peserta" onClose={()=>setEditing(null)}><Form key={editing.id} onSave={async d=>{await mutate({action:"participant.edit",participantId:editing.id,name:text(d,"name"),meetingPoint:text(d,"mepo"),facility:text(d,"facility") as "Full Transport"|"Non Transport",raincoats:number(d,"rain"),reason:text(d,"reason")});setEditing(null);}}><Field label="Nama lengkap" name="name" defaultValue={editing.name} required/><Field label="Meeting point" name="mepo" defaultValue={editing.meetingPoint} required/><label className="form-label">Fasilitas<select className="td-input" name="facility" defaultValue={editing.facility}><option>Full Transport</option><option>Non Transport</option></select></label><Field label="Jumlah jas hujan" type="number" min={0} name="rain" defaultValue={editing.raincoats??0} required/><Field label="Alasan / catatan konfirmasi" name="reason" required placeholder="Contoh: telah dikonfirmasi oleh peserta"/><Submit>Konfirmasi & simpan</Submit></Form><details className="cancel-details"><summary>Peserta membatalkan perjalanan?</summary><Form onSave={async d=>{await mutate({action:"participant.cancel",participantId:editing.id,reason:text(d,"reason")});setEditing(null);}}><Field label="Alasan pembatalan" name="reason" required/><Submit>Batalkan keikutsertaan</Submit></Form></details></Modal>}
 {proof&&<Modal title="Bukti pembayaran" onClose={()=>setProof(null)}><Evidence person={proof}/></Modal>}
 {selected.length>0&&<Modal title={selected.length>1?"Verifikasi pembayaran rombongan":"Verifikasi pembayaran"} onClose={()=>setSelected([])} wide><div className="verification-grid"><div><Evidence person={chosen[0]}/><p className="evidence-caption"><ShieldInfo/> Pastikan penerima, nominal, dan transaksi sesuai sebelum menyimpan.</p></div><div><div className="payment-summary"><span>Peserta yang diverifikasi</span><strong>{chosen.map(p=>p.name).join(", ")}</strong><div><span>Sisa tagihan</span><b>{formatRupiah(remaining)}</b></div></div><Form onSave={async d=>{await mutate({action:"payment.verify",participantIds:selected,amount,method:text(d,"method") as "transfer"|"cash"|"other",notes:text(d,"notes"),fullyPaid:d.get("fullyPaid")==="on"});setSelected([]);}}><Field label="Nominal transfer aktual (Rp)" type="number" min={1} required value={amount} onChange={e=>setAmount(Number(e.target.value))}/><label className="form-label">Metode pembayaran<select className="td-input" name="method"><option value="transfer">Transfer bank</option><option value="cash">Tunai</option><option value="other">Lainnya</option></select></label><Field label="Catatan (opsional)" name="notes" maxLength={500} placeholder="Tambahkan catatan verifikasi"/><p className="empty-note">Tanggal kas mengikuti timestamp pendaftaran{selected.length>1?" paling awal di grup":""}. {selected.length>1?"Alokasi mengikuti urutan nama; kelebihan menjadi dana belum dialokasikan.":""}</p><label className="check-label"><input type="checkbox" name="fullyPaid"/> Tandai lunas jika nominal mencukupi</label><label className="check-label"><input type="checkbox" required/> Saya telah memeriksa bukti dan nominal transfer.</label><Submit><Check size={15}/> Simpan verifikasi</Submit></Form></div></div></Modal>}
 </div>;
 function Evidence({person}:{person:Person}){const booking=state.bookings.find(b=>b.id===person.bookingId);return <div className="evidence-preview"><div className="evidence-stamp"><FileCheck2 size={32}/></div><span className="eyebrow">{prototype?"CONTOH BUKTI · SIMULASI":"BUKTI PEMBAYARAN"}</span><h3>{person.name}</h3><p>{prototype?"Area pratinjau bukti transfer":"Periksa bukti transfer di Google Drive"}</p><div className="receipt-line"><span>Trip</span><strong>{state.trips.find(t=>t.id===person.tripId)?.title}</strong></div><div className="receipt-line"><span>Tagihan peserta</span><strong>{formatRupiah(person.charge)}</strong></div><div className="receipt-line"><span>Pendaftaran</span><strong>{booking?new Date(booking.registeredAt).toLocaleDateString("id-ID"):"—"}</strong></div>{prototype?<p className="simulation-caption">Bukan bukti bank atau transaksi asli.<br/>Disediakan untuk mencoba alur review.</p>:booking?.proof&&<a className="td-secondary mt-5" href={booking.proof} target="_blank" rel="noopener noreferrer"><ExternalLink size={14}/> Buka bukti asli</a>}</div>;}
}
function ShieldInfo(){return <CircleAlert size={15}/>;}
