"use client";
import { useState } from "react";
import { Search, SlidersHorizontal, Check, Users, Wallet, Clock3, FileCheck2, ExternalLink, Pencil, ArrowRight, CircleAlert } from "lucide-react";
import { formatRupiah } from "@/lib/money";
import { paidFor, type Person } from "@/lib/workspace/types";
import { useWorkspace } from "./context";
import { Field, Form, number, Panel, Select, Submit, text, TripSelect, Modal } from "./ui";
import { ProofImage } from "./proof-image";
import { PaymentReview } from "./payment-review";
import { pendingProofs } from "@/lib/workspace/payment-queue";
export function Participants({fixedTripId}:{fixedTripId?:string}) {
 const {state,mutate}=useWorkspace();
 const [tripId,setTripId]=useState(fixedTripId??"");const [search,setSearch]=useState("");const [status,setStatus]=useState("");const [mepo,setMepo]=useState("");const [facility,setFacility]=useState("");const [filters,setFilters]=useState(false);const [page,setPage]=useState(0);const [sort,setSort]=useState("source");
 const [reviewing,setReviewing]=useState(false);const [editing,setEditing]=useState<Person|null>(null);const [selected,setSelected]=useState<string[]>([]);const [amount,setAmount]=useState(0);const [proof,setProof]=useState<Person|null>(null);
 const billStatus=(p:Person)=>!p.reviewed?"review":paidFor(state,p.id)>=p.charge?"paid":paidFor(state,p.id)>0?"dp":"unpaid";
 const labels:Record<string,string>={review:"Needs review",paid:"Paid",dp:"Deposit",unpaid:"Unpaid"};
 const pendingCount=pendingProofs(state,tripId||undefined).length;
 const active=state.participants.filter(p=>p.status==="active"&&(!tripId||p.tripId===tripId));
 const filtered=active.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())&&(!status||billStatus(p)===status)&&(!mepo||p.meetingPoint===mepo)&&(!facility||p.facility===facility));
 if(sort==="name")filtered.sort((a,b)=>a.name.localeCompare(b.name,"id"));
 if(sort==="remaining")filtered.sort((a,b)=>(b.charge-paidFor(state,b.id))-(a.charge-paidFor(state,a.id)));
 const currentPage=Math.min(page,Math.max(0,Math.ceil(filtered.length/10)-1));
 const chosen=selected.map(id=>state.participants.find(p=>p.id===id)!).filter(Boolean);
 const remaining=chosen.reduce((s,p)=>s+Math.max(p.charge-paidFor(state,p.id),0),0);
 function choose(ids:string[]){setSelected(ids);setAmount(ids.reduce((s,id)=>{const p=state.participants.find(p=>p.id===id)!;return s+Math.max(p.charge-paidFor(state,id),0);},0));}
 const counters=[{label:"Registered participants",value:active.length,icon:Users},{label:"Fully paid",value:active.filter(p=>billStatus(p)==="paid").length,icon:Check},{label:"Deposit payment",value:active.filter(p=>billStatus(p)==="dp").length,icon:Wallet},{label:"Needs follow-up",value:active.filter(p=>["unpaid","review"].includes(billStatus(p))).length,icon:Clock3}];
 return <div className="section-stack">{!fixedTripId&&<div className="stats-grid participant-stats">{counters.map(c=><div className="stat-card" key={c.label}><div className="stat-top"><span>{c.label}</span><span className="stat-icon"><c.icon size={16}/></span></div><div className="stat-value">{c.value}<small> people</small></div></div>)}</div>}
 <section className="td-panel participants-panel"><div className="panel-heading"><div><h2>Participant list</h2></div><div className="pr-heading-actions">{pendingCount>0&&<button className="td-button" onClick={()=>setReviewing(true)}><FileCheck2 size={15}/> Review payments ({pendingCount})</button>}{!fixedTripId&&<div className="compact-select"><TripSelect value={tripId} onChange={v=>{setTripId(v);setPage(0);}}/></div>}</div></div>
 <div className="status-tabs" role="group" aria-label="Filter by payment status">{[["","All participants"],["paid","Paid"],["dp","Deposit"],["unpaid","Unpaid"],["review","Needs review"]].map(([v,l])=><button key={v} aria-pressed={status===v} className={status===v?"active":""} onClick={()=>{setStatus(v);setPage(0);}}>{l}<span>{v?active.filter(p=>billStatus(p)===v).length:active.length}</span></button>)}</div>
 <div className="table-toolbar"><label className="search-field"><Search size={16}/><input aria-label="Search participant name" placeholder="Search participant name…" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label><button className="td-secondary" aria-expanded={filters} onClick={()=>setFilters(!filters)}><SlidersHorizontal size={14}/> Filter</button><div className="sort-select"><Select label="Sort" value={sort} onChange={setSort}><option value="source">Registration order</option><option value="name">Name A–Z</option><option value="remaining">Largest outstanding</option></Select></div></div>
 {filters&&<div className="filter-expand"><Select label="Meeting point" value={mepo} onChange={setMepo}><option value="">All meeting points</option>{[...new Set(active.map(p=>p.meetingPoint))].filter(Boolean).map(v=><option key={v}>{v}</option>)}</Select><Select label="Fasilitas" value={facility} onChange={setFacility}><option value="">All packages</option><option>Full Transport</option><option>Non Transport</option></Select></div>}
 <div className="table-wrap"><table className="td-table pt-table"><thead><tr>{["No","Participant","Package / meeting point","Bill","Paid","Outstanding","Status","Actions"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{filtered.slice(currentPage*10,currentPage*10+10).map((p,index)=>{const booking=state.bookings.find(b=>b.id===p.bookingId)!;const paid=paidFor(state,p.id);const group=active.filter(m=>m.tripId===p.tripId&&state.bookings.find(b=>b.id===m.bookingId)?.proof===booking.proof&&paidFor(state,m.id)<m.charge);return <tr key={p.id}><td className="row-number">{currentPage*10+index+1}</td><td><div className="overview-table-avatar"><div><strong>{p.name}</strong><small>{p.raincoats?`+ ${p.raincoats} raincoat(s)`:p.raincoats===null?"Raincoat needs review":"No add-ons"}</small></div></div>{booking.proof&&<button className="proof-link" onClick={()=>setProof(p)}><FileCheck2 size={11}/> View proof</button>}</td><td>{p.facility}<small className="block mt-1">{p.meetingPoint||"Meeting point missing"}</small></td><td className="money-cell">{formatRupiah(p.charge)}{!p.reviewed&&<small className="block">Provisional</small>}</td><td className="money-cell">{formatRupiah(paid)}</td><td className={`money-cell ${p.charge>paid?"remaining-money":""}`}>{formatRupiah(Math.max(p.charge-paid,0))}</td><td><span className={`pt-status pt-status-${billStatus(p)}`}>{labels[billStatus(p)]}</span></td><td><div className="row-actions"><button className="table-icon" aria-label={`Review ${p.name}`} onClick={()=>setEditing(p)}><Pencil size={13}/></button>{p.reviewed&&paid<p.charge&&<button className="verify-small" onClick={()=>choose([p.id])}>Verify <ArrowRight size={11}/></button>}{booking.proof&&group.length>1&&<button className="group-small" onClick={()=>choose(group.map(m=>m.id))}><Users size={12}/> Group {group.length}</button>}</div></td></tr>;})}</tbody></table>{!filtered.length&&<div className="empty-state"><Search size={26}/><h3>No matching participants</h3><p>Try another name or filter, or import responses from the Trips menu.</p></div>}</div>
 {filtered.length>10&&<div className="table-foot"><span>Showing {Math.min(currentPage*10+1,filtered.length)}–{Math.min((currentPage+1)*10,filtered.length)} of {filtered.length} participants</span><div className="pagination"><button disabled={currentPage===0} onClick={()=>setPage(currentPage-1)}>Previous</button><span>{currentPage+1}</span><button disabled={(currentPage+1)*10>=filtered.length} onClick={()=>setPage(currentPage+1)}>Next</button></div></div>}</section>
 {editing&&<Modal title="Review participant data" onClose={()=>setEditing(null)}><Form key={editing.id} onSave={async d=>{await mutate({action:"participant.edit",participantId:editing.id,name:text(d,"name"),meetingPoint:text(d,"mepo"),facility:text(d,"facility") as "Full Transport"|"Non Transport",raincoats:number(d,"rain"),reason:text(d,"reason")});setEditing(null);}}><Field label="Full name" name="name" defaultValue={editing.name} required/><Field label="Meeting point" name="mepo" defaultValue={editing.meetingPoint} required/><label className="form-label">Package<select className="td-input" name="facility" defaultValue={editing.facility}><option>Full Transport</option><option>Non Transport</option></select></label><Field label="Raincoats" type="number" min={0} name="rain" defaultValue={editing.raincoats??0} required/><Field label="Reason / confirmation note" name="reason" required placeholder="Example: confirmed by the participant"/><Submit>Confirm & save</Submit></Form><details className="cancel-details"><summary>Participant cancelling the trip?</summary><Form onSave={async d=>{await mutate({action:"participant.cancel",participantId:editing.id,reason:text(d,"reason")});setEditing(null);}}><Field label="Cancellation reason" name="reason" required/><Submit>Cancel participation</Submit></Form></details></Modal>}
 {reviewing&&<PaymentReview tripId={tripId||undefined} onClose={()=>setReviewing(false)} onReviewBill={setEditing}/>}
 {proof&&<Modal title="Payment proof" onClose={()=>setProof(null)}><Evidence person={proof}/></Modal>}
 {selected.length>0&&<Modal title={selected.length>1?"Verify group payment":"Verify payment"} onClose={()=>setSelected([])} wide><div className="verification-grid"><div><Evidence person={chosen[0]}/><p className="evidence-caption"><ShieldInfo/> Check the recipient, amount, and transaction before saving.</p></div><div><div className="payment-summary"><span>Participants being verified</span><strong>{chosen.map(p=>p.name).join(", ")}</strong><div><span>Outstanding</span><b>{formatRupiah(remaining)}</b></div></div><Form onSave={async d=>{await mutate({action:"payment.verify",participantIds:selected,amount,method:text(d,"method") as "transfer"|"cash"|"other",notes:text(d,"notes"),fullyPaid:d.get("fullyPaid")==="on"});setSelected([]);}}><Field label="Actual transfer amount (Rp)" type="number" min={1} required value={amount} onChange={e=>setAmount(Number(e.target.value))}/><label className="form-label">Payment method<select className="td-input" name="method"><option value="transfer">Bank transfer</option><option value="cash">Cash</option><option value="other">Other</option></select></label><Field label="Note (optional)" name="notes" maxLength={500} placeholder="Add a verification note"/><p className="empty-note">The cash date follows the {selected.length>1?"earliest ":""}registration timestamp{selected.length>1?" in the group":""}. {selected.length>1?"Allocation follows name order; any excess becomes unallocated funds.":""}</p><label className="check-label"><input type="checkbox" name="fullyPaid"/> Tandai lunas jika nominal mencukupi</label><label className="check-label"><input type="checkbox" required/> I have checked the proof and transfer amount.</label><Submit><Check size={15}/> Save verification</Submit></Form></div></div></Modal>}
 </div>;
 function Evidence({person}:{person:Person}){const booking=state.bookings.find(b=>b.id===person.bookingId);return <div className="evidence-preview"><div className="evidence-stamp"><FileCheck2 size={32}/></div><span className="eyebrow">{"PAYMENT PROOF"}</span><h3>{person.name}</h3><p>{"Check the transfer proof in Google Drive"}</p><div className="receipt-line"><span>Trip</span><strong>{state.trips.find(t=>t.id===person.tripId)?.title}</strong></div><div className="receipt-line"><span>Participant bill</span><strong>{formatRupiah(person.charge)}</strong></div><div className="receipt-line"><span>Registration</span><strong>{booking?new Date(booking.registeredAt).toLocaleDateString("en-GB"):"—"}</strong></div>{booking?.proof&&<ProofImage url={booking.proof}/>}{booking?.proof&&<a className="td-secondary mt-5" href={booking.proof} target="_blank" rel="noopener noreferrer"><ExternalLink size={14}/> Open original proof</a>}</div>;}
}
function ShieldInfo(){return <CircleAlert size={15}/>;}
