"use client";
import { useEffect, useState } from "react";
import { Plus, Mountain, CalendarDays, MapPin, Users, ArrowRight, FileSpreadsheet, Link2, Check, RefreshCw, Archive, SlidersHorizontal } from "lucide-react";
import { formatRupiah } from "@/lib/money";
import { useWorkspace, requestJson } from "./context";
import { Field, Form, number, Panel, Select, Submit, text, TripSelect, Modal } from "./ui";
import { Landscape } from "./landscape";
type Preview={spreadsheetId:string;sheetId:number;sheetTitle:string;headerRow:number;headers:string[];sheets:{sheetId:number;title:string}[];mapping:{field:string;index:number|null;required:boolean}[];preview:Record<string,string>[]};
const labels:Record<string,string>={registered_at:"Timestamp pendaftaran",raw_name:"Nama peserta",facility:"Fasilitas",meeting_point:"MEPO",raincoat_option:"Jas hujan",proof_refs:"Bukti transfer",contact_phone:"WhatsApp"};
export function Trips(){
 const {state,revision,mutate,replace,run,busy,prototype}=useWorkspace();
 const [tripId,setTripId]=useState(state.trips[0]?.id??"");const [preview,setPreview]=useState<Preview|null>(null);const [mapping,setMapping]=useState<Record<string,number>>({});const [sheetId,setSheetId]=useState("");const [creating,setCreating]=useState(false);const [tab,setTab]=useState("active");
 const source=state.sources.find(s=>s.tripId===tripId);
 useEffect(()=>{if(window.location.hash==="#buat-trip")queueMicrotask(()=>setCreating(true));},[]);
 async function sync(){
   if(!prototype){if(source)replace(await requestJson("/api/sync/run",{...source,revision}));return;}
   const next=structuredClone(state);const saved=next.sources.find(s=>s.tripId===tripId);const now=new Date().toISOString();
   if(saved)saved.lastSuccessAt=now;
   else if(preview)next.sources.push({id:crypto.randomUUID(),tripId,spreadsheetId:preview.spreadsheetId,sheetId:preview.sheetId,sheetTitle:preview.sheetTitle,headerRow:preview.headerRow,headers:preview.headers,mapping,lastSuccessAt:now,review:[]});
   next.audit.push({id:crypto.randomUUID(),userId:"demo",at:now,action:"sync.completed",detail:`Simulasi sinkronisasi ${next.trips.find(t=>t.id===tripId)?.title}; tidak ada respons baru`});
   replace({state:next,revision:revision+1});
 }
 const trips=state.trips.filter(t=>tab==="all"||t.status===tab);
 return <div className="section-stack"><div className="trip-list-toolbar"><div className="status-tabs" role="group" aria-label="Status trip">{[["active","Trip aktif"],["archived","Diarsipkan"],["all","Semua trip"]].map(([v,l])=><button key={v} className={tab===v?"active":""} aria-pressed={tab===v} onClick={()=>setTab(v)}>{l}<span>{state.trips.filter(t=>v==="all"||t.status===v).length}</span></button>)}</div><button className="td-button" onClick={()=>setCreating(true)}><Plus size={15}/> Buat Trip</button></div>
 <div className="trip-card-grid">{trips.map((trip,i)=>{const count=state.participants.filter(p=>p.tripId===trip.id&&p.status==="active").length;return <article className="trip-card" key={trip.id}><div className="trip-card-cover"><Landscape variant={i%3}/><span className="trip-number">OPEN TRIP / {String(i+1).padStart(2,"0")}</span><span className="badge">{trip.status==="active"?"Aktif":"Arsip"}</span></div><div className="trip-card-body"><div className="eyebrow">EXPLORE THE OUTDOORS</div><h2>{trip.title}</h2><div className="trip-card-meta"><span><CalendarDays size={13}/>{new Date(`${trip.departureDate}T12:00:00`).toLocaleDateString("id-ID",{day:"numeric",month:"long",year:"numeric"})}</span><span><Users size={13}/>{count} peserta terdaftar</span></div><div className="trip-pricing"><span>Mulai dari<strong>{formatRupiah(trip.nonPrice)}<small> / orang</small></strong></span><Mountain size={21}/></div><div className="trip-card-actions"><button className="td-secondary" onClick={()=>{setTripId(trip.id);document.getElementById("impor")?.scrollIntoView({behavior:"smooth"});}}><FileSpreadsheet size={13}/> Kelola sumber</button><button className="table-icon" disabled={busy} aria-label={`${trip.status==="active"?"Arsipkan":"Aktifkan"} ${trip.title}`} onClick={()=>void run(()=>mutate({action:"trip.status",tripId:trip.id,status:trip.status==="active"?"archived":"active"}))}><Archive size={15}/></button></div></div></article>;})}</div>{!trips.length&&<div className="empty-state"><Mountain size={30}/><h3>Belum ada trip di sini</h3><p>Tambahkan perjalanan baru untuk mulai mengelola peserta.</p></div>}
 <div id="impor" className="scroll-target"><Panel title="Hubungkan data pendaftaran"><div className="import-intro"><div className="integration-icon"><FileSpreadsheet size={28}/></div><div><h3>Google Spreadsheet → TripDash</h3><p>Respons Google Form, otomatis tertata menjadi daftar peserta.</p></div>{prototype&&<span className="badge amber">Simulasi impor</span>}</div><div className="import-steps"><span className="active"><b>1</b> Pilih sumber</span><i/><span className={preview?"active":""}><b>2</b> Tinjau mapping</span><i/><span><b>3</b> Sinkronkan</span></div>
 <TripSelect value={tripId} onChange={v=>{setTripId(v);setPreview(null);setSheetId("");}} all="Pilih trip"/>
 {tripId&&<Form onSave={async d=>{let p:Preview;if(prototype){if(!text(d,"url").startsWith("https://docs.google.com/spreadsheets/"))throw new Error("Gunakan URL Google Spreadsheet untuk simulasi.");const headers=["Timestamp","Nama Lengkap","Fasilitas","Mepo","Jas Hujan (+15k)","Registrasi"];p={spreadsheetId:"prototype-spreadsheet-malabar",sheetId:0,sheetTitle:"Form Responses 1",headerRow:number(d,"header"),headers,sheets:[{sheetId:0,title:"Form Responses 1"}],mapping:Object.keys(labels).map((field,index)=>({field,index:index<6?index:null,required:index<4})),preview:[{raw_name:"Ardi Pratama"},{raw_name:"Nadia Putri"},{raw_name:"Bima + Galih + Rafi"}]};}else p=await requestJson("/api/sync/connect",{tripId,spreadsheetUrl:text(d,"url"),headerRow:number(d,"header"),...(sheetId!==""?{sheetId:Number(sheetId)}:{})});setPreview(p);setMapping(Object.fromEntries(p.mapping.filter(m=>m.index!==null).map(m=>[m.field,m.index!])));}}><div className="import-source-fields"><Field key={tripId} label="Tautan Google Spreadsheet" name="url" type="url" defaultValue={source?`https://docs.google.com/spreadsheets/d/${source.spreadsheetId}/edit`:prototype?"https://docs.google.com/spreadsheets/d/contoh-respons-trip/edit":""} placeholder="https://docs.google.com/spreadsheets/d/…" required/><Field label="Baris header" name="header" type="number" min={1} max={100} defaultValue={1} required/></div>{preview&&<Select label="Tab spreadsheet" value={sheetId||String(preview.sheetId)} onChange={v=>{setSheetId(v);setPreview({...preview,mapping:[]});}}>{preview.sheets.map(s=><option key={s.sheetId} value={s.sheetId}>{s.title}</option>)}</Select>}<div><Submit><Link2 size={14}/> Preview & petakan kolom</Submit></div></Form>}
 {preview&&preview.mapping.length>0&&<div className="mapping-preview"><h3><SlidersHorizontal size={16}/> Pemetaan kolom</h3><p>Pastikan kolom sumber sesuai dengan data yang dibutuhkan.</p><div className="mapping-grid">{preview.mapping.map(m=><Select key={m.field} label={`${labels[m.field]}${m.required?" *":""}`} value={mapping[m.field]===undefined?"":String(mapping[m.field])} onChange={v=>setMapping(old=>{const next={...old};if(v==="")delete next[m.field];else next[m.field]=Number(v);return next;})}><option value="">Tidak dipetakan</option>{preview.headers.map((h,i)=><option key={i} value={i}>{h.slice(0,100)}</option>)}</Select>)}</div><p className="empty-note">Contoh nama: {preview.preview.map(p=>p.raw_name).join(" · ")}. Nama gabungan dipisah menjadi peserta berbeda.</p><button className="td-button" disabled={busy} onClick={()=>void run(async()=>{for(const key of ["registered_at","raw_name","facility","meeting_point"])if(mapping[key]===undefined)throw new Error(`Pilih kolom ${labels[key]}.`);if(new Set(Object.values(mapping)).size!==Object.values(mapping).length)throw new Error("Satu kolom hanya dapat dipetakan sekali.");if(prototype)await sync();else replace(await requestJson("/api/sync/run",{tripId,revision,...preview,mapping}));setPreview(null);})}><Check size={14}/> Konfirmasi & sinkronkan</button></div>}
 {source&&<div className="sync-status"><span><span className="status-dot"/> Terakhir sinkron: {new Date(source.lastSuccessAt).toLocaleString("id-ID",{timeZone:"Asia/Jakarta",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"})} WIB</span><button className="text-link" disabled={busy} onClick={()=>void run(sync)}><RefreshCw size={13}/> Sinkronkan sekarang</button></div>}{source?.review.map((r,i)=><p className="inline-warning" key={i}>{r}</p>)}</Panel></div>
 {creating&&<Modal title="Buat perjalanan baru" onClose={()=>setCreating(false)}><Form onSave={async d=>{await mutate({action:"trip.create",title:text(d,"title"),departureDate:text(d,"date"),fullPrice:number(d,"full"),nonPrice:number(d,"non"),raincoatPrice:number(d,"rain")});setCreating(false);}}><Field label="Nama trip" name="title" required maxLength={200} placeholder="Contoh: Papandayan Sunrise"/><Field label="Tanggal keberangkatan" type="date" name="date" required/><div className="price-form"><Field label="Full Transport (Rp)" type="number" name="full" min={0} defaultValue={175000} required/><Field label="Non Transport (Rp)" type="number" name="non" min={0} defaultValue={110000} required/></div><Field label="Jas hujan per buah (Rp)" type="number" name="rain" min={0} defaultValue={15000} required/><p className="empty-note">Harga berlaku per orang. Tinjau tarif sebelum membuat trip.</p><Submit><Plus size={15}/> Buat Trip</Submit></Form></Modal>}
 </div>;
}
