import { AttendanceDocument, AttendanceParticipant } from "./types";

const escapeHtml = (value: unknown) => String(value ?? "").replace(/[&<>\"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;" })[character] ?? character);
const formatDate = (date: Date) => date.toLocaleString("id-ID", { timeZone: "Asia/Jakarta" });

export function renderAttendanceTemplate(document: AttendanceDocument, participants: AttendanceParticipant[]) {
  const rows = participants.map((participant, index) => `<tr><td class="number">${index + 1}</td><td>${escapeHtml(participant.name)}</td><td>${escapeHtml(participant.meetingPoint)}</td><td></td><td></td><td></td></tr>`).join("");
  return `<!doctype html><html lang="id"><head><meta charset="utf-8"><title>${escapeHtml(document.title)}</title><style>
@page{size:A4 portrait;margin:16mm 14mm 18mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#111;font-size:10pt;margin:0}header{text-align:center;margin-bottom:14px}h1{font-size:17pt;margin:0 0 6px;text-transform:uppercase}p{margin:3px 0}.meta{font-size:9pt;color:#444}table{border-collapse:collapse;width:100%;table-layout:fixed;break-inside:auto}thead{display:table-header-group}tr{break-inside:avoid}th,td{border:1px solid #111;padding:6px 5px;vertical-align:top;overflow-wrap:anywhere;white-space:normal;min-height:26px}th{background:#eee;text-align:center;font-size:9pt}.number{text-align:center;width:7%}th:nth-child(2){width:28%}th:nth-child(3){width:22%}th:nth-child(4){width:16%}th:nth-child(5){width:13%}th:nth-child(6){width:14%}footer{position:fixed;bottom:-10mm;left:0;right:0;display:flex;justify-content:space-between;font-size:8pt;color:#555}</style></head><body><header><h1>${escapeHtml(document.title)}</h1><p>Penyelenggara: ${escapeHtml(document.organizer)}</p><p class="meta">Waktu Snapshot: ${escapeHtml(formatDate(document.snapshotAt))}</p></header><table><thead><tr><th>NO</th><th>NAMA</th><th>MEPO</th><th>BASECAMP</th><th>MAKAN</th><th>PULANG</th></tr></thead><tbody>${rows}</tbody></table><footer><span>OpenTrip Dash · Snapshot v${document.version}</span><span>${escapeHtml(formatDate(document.snapshotAt))}</span></footer></body></html>`;
}
