"use client";
import { Suspense, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { useAuth } from "@/lib/auth/context";
import { ArrowRight, Compass, Mountain, Eye, EyeOff, ShieldCheck } from "lucide-react";
import Link from "next/link";
import Image from "next/image";
import { Landscape } from "@/components/tripdash/landscape";
function LoginForm(){
 const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(false);const [showPassword,setShowPassword]=useState(false);
 const params=useSearchParams();const router=useRouter();const {login}=useAuth();
 return <main className="login-layout"><section className="login-story"><Link href="/prototype" className="brand-lockup"><Image src="/brand/rimbaloka-logo.jpeg" alt="Rimbaloka Trip" width={48} height={48}/><div><strong>rimbaloka<span>.</span></strong><small>TRIP MANAGEMENT</small></div></Link><div className="login-story-copy"><span className="eyebrow">ADVENTURE, WELL MANAGED.</span><h1>Urus perjalanannya.<br/>Nikmati ceritanya.</h1><p>Ruang kerja untuk setiap petualangan.<br/>Dari pendaftaran pertama sampai langkah terakhir.</p></div><div className="login-landscape"><Landscape/></div><span className="login-story-foot"><Mountain size={16}/> Lebih dekat dengan alam.</span></section><section className="login-form-side"><div className="login-form-wrap"><span className="eyebrow">SELAMAT DATANG DI TRIPDASH</span><h2>Siap melanjutkan<br/>perjalanan?</h2><p>Masuk untuk mengelola operasional Rimbaloka Trip.</p>{params.get("registered")==="1"&&<p role="status" className="notice">Akun berhasil dibuat. Periksa email konfirmasi, lalu masuk.</p>}{error&&<p className="notice error" role="alert">{error}</p>}<form onSubmit={async e=>{e.preventDefault();setError("");setLoading(true);try{const result=await login(email,password);if(result.success){router.push("/dashboard");router.refresh();}else setError(result.error??"Login gagal.");}catch{setError("Login gagal. Silakan coba kembali.");}finally{setLoading(false);}}}><label className="form-label">Alamat email<input type="email" className="td-input" autoComplete="email" placeholder="nama@rimbaloka.com" value={email} onChange={e=>setEmail(e.target.value)} required disabled={loading}/></label><label className="form-label">Password<div className="password-input"><input className="td-input" autoComplete="current-password" type={showPassword?"text":"password"} placeholder="Masukkan password" value={password} onChange={e=>setPassword(e.target.value)} required disabled={loading}/><button type="button" aria-label={showPassword?"Sembunyikan password":"Tampilkan password"} onClick={()=>setShowPassword(!showPassword)}>{showPassword?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label><button className="td-button" type="submit" disabled={loading}>{loading?"Memproses…":"Masuk ke workspace"}<ArrowRight size={15}/></button></form><div className="login-divider"><span>atau jelajahi terlebih dahulu</span></div><Link href="/prototype" className="td-secondary w-full"><Compass size={15}/> Coba prototipe interaktif</Link><p className="login-register">Belum memiliki akun? <Link href="/register">Daftar bisnis Anda</Link></p><div className="login-security"><ShieldCheck size={14}/> Akses aman untuk ruang kerja bisnis Anda.</div></div><footer>© 2026 Rimbaloka Trip · TripDash</footer></section></main>;
}
export default function LoginPage(){return <Suspense fallback={<p>Memuat login…</p>}><LoginForm/></Suspense>;}
