import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
const origin = process.env.PROTOTYPE_URL || 'http://localhost:3012';
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
await context.addInitScript(() => { window.print = () => {}; });
const page = await context.newPage();
await page.route('**/api/sync/public', async route=>{
  const body=route.request().postDataJSON();
  const id=new URL(body.spreadsheetUrl).pathname.split('/d/')[1].split('/')[0];
  await route.fulfill({json:{metadata:{spreadsheetId:id,title:'Perjalanan contoh impor (Responses)'},sheet:{sheetId:0,title:'Form Responses 1'},values:[['Timestamp','Nama Lengkap','Fasilitas','Mepo'],['13/09/2026 08:00:00','Peserta Contoh A','Full Transport','Bandung'],['13/09/2026 08:05:00','Peserta Contoh B','Non Transport','Basecamp']]}});
});
const errors = [], api = [];
page.on('pageerror', error => errors.push(error.message));
page.on('request', request => { if (new URL(request.url()).pathname.startsWith('/api/') && !request.url().includes('/api/sync/public')) api.push(request.url()); });
mkdirSync('artifacts', { recursive: true });
const state = () => page.evaluate(() => JSON.parse(localStorage.getItem('rimbaloka-prototype-v1')).state);
const goto = async path => { await page.goto(origin + path, { waitUntil: 'networkidle' }); };
const shot = async name => { await page.evaluate(() => window.scrollTo(0, 0)); await page.screenshot({ path: `artifacts/prd-${name}.png`, fullPage: true }); };
try {
  await goto('/prototype');
  await page.getByRole('button', { name: 'Reset data simulasi' }).click();
  await page.reload({ waitUntil: 'networkidle' });
  const initial = await state(), tripId = initial.trips[0].id;
  assert.equal(await page.getByRole('navigation').getByRole('link').count(), 4);
  assert.equal(await page.locator('.app-topbar,.hero-banner,.sidebar-note').count(), 0);
  assert.equal(await page.title(), 'TripDash');
  assert.equal(await page.locator('.overview-brief').count(), 0);
  for (const copy of ['Seluruh perjalanan', 'Lihat perjalanan', 'Di bawah minimum peserta']) assert.equal(await page.getByText(copy, {exact:true}).count(),0);
  const colors = await page.locator('.overview-counts details').evaluateAll(rows=>rows.map(el=>getComputedStyle(el).backgroundColor));
  assert.equal(new Set(colors).size,4);
  await shot('overview-desktop');
  await page.getByRole('button', { name: 'Ringkas navigasi', exact: true }).click();
  assert.equal(await page.locator('.forest-sidebar').evaluate(el => el.getBoundingClientRect().width), 80);
  await page.getByRole('button', { name: 'Perluas navigasi', exact: true }).click();
  await page.locator('.count-upcoming summary').click();
  await page.locator('.count-upcoming .count-dropdown a').first().click();
  await page.waitForURL(`${origin}/prototype/trips/${tripId}`);
  assert.equal(await page.locator('.participants-panel tbody tr').count(), 10);
  assert.equal(await page.locator('.row-number').first().innerText(), '1');
  await page.getByRole('button', { name: 'Berikutnya', exact: true }).click();
  assert.equal(await page.locator('.row-number').first().innerText(), '11');
  await page.getByRole('textbox', { name: 'Cari nama peserta' }).fill('Bima');
  await page.getByRole('button', { name: 'Grup 3', exact: true }).click();
  await page.getByLabel('Nominal transfer aktual (Rp)').fill('230000');
  await page.getByLabel('Tandai lunas jika nominal mencukupi').check();
  await page.getByLabel('Saya telah memeriksa bukti dan nominal transfer.').check();
  const before = (await state()).cash.length;
  await page.getByRole('button', { name: 'Simpan verifikasi' }).click();
  await page.getByRole('dialog').waitFor({ state: 'detached' });
  assert.equal((await state()).cash.length, before + 1);
  await page.getByRole('textbox', { name: 'Cari nama peserta' }).fill('');
  const popupPromise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Cetak / simpan PDF' }).click();
  const popup = await popupPromise; await popup.waitForLoadState();
  assert.equal(await popup.locator('tbody tr').count(), 21);
  const mepos = await popup.locator('tbody tr td:nth-child(3)').allTextContents();
  assert.deepEqual(mepos, [...mepos].sort((a, b) => a.localeCompare(b, 'id')));
  await popup.close();
  await page.reload({ waitUntil: 'networkidle' });
  assert.equal((await state()).cash.length, before + 1);
  await shot('trip-detail-desktop');
  await page.getByRole('button', { name: 'Edit trip', exact: true }).click();
  await page.getByLabel('Lokasi', { exact: true }).fill('Pangalengan');
  await page.getByRole('button', { name: 'Simpan trip', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'detached' });
  assert.equal((await state()).trips[0].location, 'Pangalengan');
  await page.getByRole('button', { name: 'Impor spreadsheet', exact: true }).click();
  assert.equal(await page.getByLabel('Baris header', {exact:true}).count(),0);
  assert.equal(await page.getByRole('dialog').locator('input').count(),1);
  await page.getByRole('button', {name:'Impor dari tautan'}).click();
  await page.getByText('Impor selesai', {exact:true}).waitFor();
  await page.getByRole('button', { name: 'Tutup dialog' }).click();

  await goto('/prototype/trips');
  assert.equal(await page.locator('.schedule-trip').count(), 2);
  await page.getByLabel('Tampilan jadwal').selectOption('year');
  assert.equal(await page.locator('.schedule-trip').count(), 3);
  await shot('schedule-desktop');
  assert.equal(await page.getByRole('button', {name:'Buat Trip',exact:true}).count(),0);
  await page.getByRole('button', {name:'Impor spreadsheet',exact:true}).click();
  await page.getByLabel('Tautan Google Spreadsheet').fill('https://docs.google.com/spreadsheets/d/spreadsheet-new-trip-example/edit');
  await page.getByRole('button', {name:'Impor dari tautan'}).click();
  await page.getByText('Impor selesai', {exact:true}).waitFor();
  assert.equal((await state()).trips.length,4);
  const importedId=(await state()).trips.at(-1).id;
  await page.getByRole('button', {name:'Impor dari tautan'}).click();
  await page.waitForFunction(()=>JSON.parse(localStorage.getItem('rimbaloka-prototype-v1')).state.audit.at(-1).detail.includes('0 respons baru'));
  assert.equal((await state()).trips.length,4);
  await page.getByRole('button', {name:'Tutup dialog'}).click();
  assert.equal(await page.locator('.schedule-trip').count(),4);
  await goto('/prototype/trips/'+importedId);
  assert.equal(await page.locator('.participants-panel tbody tr').count(),2);
  assert.match(await page.locator('.trip-detail-heading').innerText(),/Belum dijadwalkan/);
  await page.getByRole('button', {name:'Edit trip',exact:true}).click();
  await page.getByLabel('Nama trip',{exact:true}).fill('Trip uji PRD');
  await page.getByLabel('Tanggal keberangkatan').fill('2026-09-19');
  await page.getByLabel('Minimum peserta').fill('9');
  await page.getByRole('button', {name:'Simpan trip',exact:true}).click();
  await page.getByRole('dialog').waitFor({state:'detached'});
  await goto('/prototype');
  await page.locator('.count-risk summary').click();
  assert.match(await page.locator('.count-risk .count-dropdown').innerText(), /Trip uji PRD/);

  await goto('/prototype/inventory');
  assert.equal(await page.locator('.inventory-row').count(), 8);
  assert.equal(await page.locator('.stock-reminder').count(), 2);
  await shot('inventory-desktop');
  await page.getByRole('button', { name: 'Tambah barang', exact: true }).click();
  await page.getByLabel('Nama barang').fill('Tenda uji PRD');
  await page.getByLabel('Jumlah stok total').fill('5');
  await page.getByRole('dialog').getByRole('button', { name: 'Tambah barang', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'detached' });
  await page.getByRole('button', { name: 'Berikutnya', exact: true }).click();
  assert.equal(await page.locator('.inventory-row').count(), 1);
  await page.getByLabel('Cari barang').fill('Tenda uji PRD');
  const itemRow = page.locator('.inventory-row').filter({ hasText: 'Tenda uji PRD' });
  await itemRow.getByRole('button', { name: 'Catat peminjaman' }).click();
  await page.getByLabel('Jumlah unit').fill('2');
  await page.getByLabel('Catatan peminjaman').fill('Dibawa tim logistik');
  await page.getByRole('button', { name: 'Simpan peminjaman' }).click();
  await page.getByRole('dialog').waitFor({ state: 'detached' });
  let item = (await state()).inventory.find(i => i.name === 'Tenda uji PRD');
  assert.equal(item.loans[0].quantity, 2);
  assert.equal(item.loans[0].notes,'Dibawa tim logistik');
  await itemRow.getByRole('button',{name:'Tambah catatan'}).click();
  await page.getByLabel('Catatan kejadian').fill('Tenda hilang');
  await page.getByLabel('Dampak pada stok').selectOption('lost');
  await page.getByLabel('Lokasi barang').selectOption(item.loans[0].id);
  await page.getByLabel('Jumlah barang terdampak').fill('1');
  await page.getByRole('button',{name:'Simpan catatan'}).click();
  await page.getByRole('dialog').waitFor({state:'detached'});
  assert.match(await itemRow.innerText(),/Tenda hilang/);
  assert.equal((await state()).inventory.find(i=>i.id===item.id).total,4);
  await itemRow.getByRole('button', { name: /Kembalikan/ }).click();
  await page.locator('.notice[role="status"]').waitFor();
  item = (await state()).inventory.find(i => i.name === 'Tenda uji PRD'); assert.equal(item.loans[0].returned, true);
  await itemRow.getByRole('button', { name: 'Edit Tenda uji PRD', exact: true }).click();
  await page.getByRole('button', { name: 'Tambah stok total' }).click();
  await page.getByLabel('Alasan perubahan').fill('Restok');
  await page.getByRole('button', { name: 'Simpan barang' }).click();
  await page.getByRole('dialog').waitFor({ state: 'detached' });
  assert.equal((await state()).inventory.find(i => i.id === item.id).total, 5);
  await itemRow.getByRole('button', { name: 'Hapus Tenda uji PRD', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Hapus barang', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'detached' });
  assert.equal((await state()).inventory.some(i => i.id === item.id), false);
  await page.getByLabel('Cari barang').fill('Stiker');
  await page.getByRole('button', { name: 'Catat pemakaian' }).click();
  await page.getByLabel('Jumlah unit').fill('2'); await page.getByLabel('Keperluan').fill('Malabar');
  await page.getByRole('button', { name: 'Simpan pemakaian' }).click();
  await page.getByRole('dialog').waitFor({ state: 'detached' });
  assert.equal((await state()).inventory.find(i => i.name === 'Stiker Rimbaloka').total, 6);

  await goto('/prototype/finance');
  assert.equal(await page.locator('.finance-trip-detail').count(), 0);
  assert.equal(await page.getByRole('button', { name: 'Catat pengeluaran', exact: true }).count(), 0);
  assert.match(await page.locator('.cash-balance').innerText(),/Saldo awal tercatat/);
  assert.equal(await page.locator('.expense-breakdown').count(),1);
  await shot('cashflow-desktop');
  await page.getByRole('button', { name: 'Tahunan', exact: true }).click();
  assert.equal(await page.getByLabel('Lihat bulan').locator('option').count(), 12);
  await page.getByRole('button', { name: 'Bulanan', exact: true }).click();
  await page.locator('.cash-week summary').first().click();
  await page.locator('.cash-trip').first().click();
  assert.match(await page.locator('.detail-finance-heading h2').innerText(), /Malabar/);
  await page.getByRole('button', { name: 'Catat pengeluaran', exact: true }).click();
  await page.getByLabel('Nominal pengeluaran (Rp)').fill('50000');
  await page.getByLabel('Kategori', { exact: true }).fill('Logistik uji');
  await page.getByLabel('Keterangan', { exact: true }).fill('Pengeluaran uji PRD');
  await page.getByRole('button', { name: 'Simpan pengeluaran' }).click();
  await page.getByRole('dialog').waitFor({ state: 'detached' });
  await page.getByLabel('Cari transaksi').fill('Pengeluaran uji PRD');
  assert.equal(await page.locator('.transaction-toolbar + .table-wrap tbody tr').count(), 1);
  await page.getByRole('button', { name: 'Edit Pengeluaran uji PRD' }).click();
  await page.getByLabel('Nominal pengeluaran (Rp)').fill('60000');
  await page.getByRole('button', { name: 'Simpan pengeluaran' }).click();
  await page.getByRole('dialog').waitFor({ state: 'detached' });
  assert.equal((await state()).cash.find(c => c.description === 'Pengeluaran uji PRD').amount, 60000);
  const download = page.waitForEvent('download'); await page.getByRole('button', { name: 'Ekspor CSV' }).click(); assert.equal((await download).suggestedFilename(), 'keuangan-simulasi.csv');
  await page.getByRole('button', { name: 'Hapus Pengeluaran uji PRD' }).click();
  await page.getByLabel('Alasan penghapusan').fill('Pembatalan biaya');
  await page.getByRole('button', { name: 'Hapus pengeluaran', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'detached' });
  assert.equal((await state()).cash.some(c => c.description === 'Pengeluaran uji PRD'), false);
  await page.getByLabel('Cari transaksi').fill('');
  await page.getByRole('tab',{name:/Pembayaran peserta/}).click();
  assert.equal(await page.locator('.receivables').count(),1);
  await page.getByRole('tab',{name:/Transaksi/}).click();
  assert.equal(await page.getByRole('columnheader',{name:'Saldo berjalan'}).count(),1);
  await shot('cashflow-detail-desktop');

  for (const viewport of [{ width: 375, height: 812 }, { width: 768, height: 1024 }, { width: 1024, height: 768 }, { width: 1440, height: 1000 }, { width: 812, height: 375 }]) {
    await page.setViewportSize(viewport);
    for (const section of ['', '/trips', `/trips/${tripId}`, '/inventory', '/finance', `/finance?trip=${tripId}`]) {
      await goto(`/prototype${section}`);
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Overflow at ${viewport.width} ${section}`);
      if (viewport.width === 375) await shot(`${section.includes('?') ? 'cash-detail' : section.startsWith('/trips/') ? 'trip-detail' : section.slice(1) || 'overview'}-mobile`);
    }
  }
  await page.setViewportSize({ width: 375, height: 812 });
  await page.getByRole('button', { name: 'Buka navigasi' }).click();
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.forest-sidebar').isVisible(), false);
  await page.getByRole('button', { name: 'Buka navigasi' }).click();
  await page.getByRole('navigation').getByRole('link', { name: 'Overview', exact: true }).click();
  await page.waitForURL(`${origin}/prototype`);
  await page.getByRole('button', { name: 'Reset data simulasi' }).click();
  assert.equal((await state()).trips.length, 3);
  assert.deepEqual(errors, []); assert.deepEqual(api, []);
  await page.getByRole('button',{name:'Buka navigasi'}).click();
  await page.getByRole('link',{name:'Keluar demo',exact:true}).click();
  await page.waitForURL(origin+'/login?demo=ended');
  assert.match(await page.getByRole('status').innerText(),/keluar dari demo/);
  await page.getByLabel('Password',{exact:true}).fill('test-password');
  await page.getByRole('button',{name:'Tampilkan password'}).click();
  assert.equal(await page.getByLabel('Password',{exact:true}).getAttribute('type'),'text');
  assert.equal(await page.getByRole('button',{name:'Login',exact:true}).count(),1);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await shot('login-mobile');
  await goto('/');
  assert.equal(new URL(page.url()).pathname,'/login');
  console.log('PASS: four-menu navigation; no top navbar; calendar/drilldown; trip edit and risk threshold; grouped schedule; participant pagination/group payment; 21-person PDF sorted by mepo; link-only import/new trip/deduplication; inventory pagination/create/edit/delete/lend/return/consume; cashflow period graph/drilldown/expense CRUD/CSV; persistence; mobile/tablet/desktop/landscape; inventory incident stock integrity; cashflow categories/balances/receivables; login and demo exit; reset; no prototype business API calls.');
} finally { await browser.close(); }
