import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
const origin=process.env.PROTOTYPE_URL || 'http://localhost:3012';
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
await context.addInitScript(()=>{window.print=()=>{};});
const page=await context.newPage();
const errors=[];const apiCalls=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('request',r=>{if(new URL(r.url()).pathname.startsWith('/api/'))apiCalls.push(r.url());});
mkdirSync('artifacts',{recursive:true});
const snapshot=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('rimbaloka-prototype-v1')));
try {
 await page.goto(`${origin}/prototype`,{waitUntil:'networkidle'});
 await page.getByRole('button',{name:'Reset data simulasi'}).click();
 assert.equal((await snapshot()).state.participants.length,21);
 await page.screenshot({path:'artifacts/rimbaloka-overview-desktop.png',fullPage:true});
 await page.goto(`${origin}/prototype/participants`,{waitUntil:'networkidle'});
 await page.getByRole('button',{name:'Grup 3',exact:true}).first().click();
 await page.getByRole('dialog').waitFor();
 await page.getByLabel('Nominal transfer aktual (Rp)').fill('230000');
 await page.getByLabel('Tandai lunas jika nominal mencukupi').check();
 await page.getByLabel('Saya telah memeriksa bukti dan nominal transfer.').check();
 await page.screenshot({path:'artifacts/rimbaloka-payment-modal.png',fullPage:true});
 const before=(await snapshot()).state.cash.length;
 await page.getByRole('button',{name:'Simpan verifikasi'}).click();
 await page.getByRole('dialog').waitFor({state:'detached'});
 assert.equal((await snapshot()).state.cash.length,before+1);
 await page.reload({waitUntil:'networkidle'});
 assert.equal((await snapshot()).state.cash.length,before+1);
 await page.getByRole('textbox',{name:'Cari nama peserta'}).fill('Nadia');
 assert.equal(await page.locator('tbody tr').count(),1);
 await page.getByRole('textbox',{name:'Cari nama peserta'}).fill('');
 await page.screenshot({path:'artifacts/rimbaloka-participants-desktop.png',fullPage:true});
 await page.goto(`${origin}/prototype/trips`,{waitUntil:'networkidle'});
 await page.getByRole('button',{name:'Buat Trip',exact:true}).click();
 await page.getByLabel('Nama trip',{exact:true}).fill('Trip Uji UI');
 await page.getByLabel('Tanggal keberangkatan').fill('2026-10-20');
 await page.getByRole('dialog').getByRole('button',{name:'Buat Trip',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'detached'});
 assert.equal((await snapshot()).state.trips.length,4);
 await page.getByRole('button',{name:'Preview & petakan kolom'}).click();
 await page.getByRole('button',{name:'Konfirmasi & sinkronkan'}).click();
 await page.getByRole('button',{name:'Konfirmasi & sinkronkan'}).waitFor({state:'detached'});
 await page.goto(`${origin}/prototype/inventory`,{waitUntil:'networkidle'});
 await page.getByRole('button',{name:'Tambah barang',exact:true}).click();
 await page.getByLabel('Nama barang').fill('Tenda uji browser');
 await page.getByLabel('Jumlah stok total').fill('5');
 await page.getByRole('dialog').getByRole('button',{name:'Tambah barang',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'detached'});
 let item=(await snapshot()).state.inventory.find(i=>i.name==='Tenda uji browser');assert.equal(item.total,5);
 await page.locator('.inventory-card').filter({hasText:'Tenda uji browser'}).getByRole('button',{name:'Catat barang keluar'}).click();
 await page.getByLabel('Jumlah dibawa / disewakan').fill('2');
 await page.getByRole('button',{name:'Konfirmasi barang keluar'}).click();
 await page.getByRole('dialog').waitFor({state:'detached'});
 item=(await snapshot()).state.inventory.find(i=>i.name==='Tenda uji browser');assert.equal(item.loans[0].quantity,2);
 await page.locator('.inventory-card').filter({hasText:'Tenda uji browser'}).getByRole('button',{name:/Kembalikan/}).click();
 await page.getByRole('status').waitFor();
 item=(await snapshot()).state.inventory.find(i=>i.name==='Tenda uji browser');assert.equal(item.loans[0].returned,true);
 await page.goto(`${origin}/prototype/finance`,{waitUntil:'networkidle'});
 await page.getByRole('button',{name:'Catat pengeluaran'}).click();
 await page.getByLabel('Nominal pengeluaran (Rp)').fill('50000');
 await page.getByLabel('Kategori',{exact:true}).fill('Uji logistik');
 await page.getByLabel('Keterangan',{exact:true}).fill('Pengeluaran uji browser');
 await page.getByRole('button',{name:'Simpan pengeluaran'}).click();
 await page.getByRole('dialog').waitFor({state:'detached'});
 assert.ok((await snapshot()).state.cash.some(c=>c.amount===50000&&c.category==='Uji logistik'));
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Ekspor CSV'}).click();assert.equal((await download).suggestedFilename(),'keuangan-simulasi.csv');
 await page.goto(`${origin}/prototype/attendance`,{waitUntil:'networkidle'});
 assert.equal(await page.locator('.attendance-paper-table tbody tr').count(),21);
 const popupPromise=page.waitForEvent('popup');await page.getByRole('button',{name:'Cetak / simpan PDF'}).click();const popup=await popupPromise;await popup.waitForLoadState();assert.equal(await popup.locator('tbody tr').count(),21);await popup.close();
 await page.screenshot({path:'artifacts/rimbaloka-attendance-desktop.png',fullPage:true});
 for(const section of ['', '/trips','/participants','/finance','/inventory','/attendance','/settings']){
  await page.setViewportSize({width:375,height:812});await page.goto(`${origin}/prototype${section}`,{waitUntil:'networkidle'});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),`Overflow: ${section}`);
  await page.screenshot({path:`artifacts/rimbaloka-${section.slice(1)||'overview'}-mobile.png`,fullPage:true});
 }
 await page.getByRole('button',{name:'Buka navigasi'}).click();await page.getByRole('navigation').getByRole('link',{name:'Ringkasan'}).click();
 await page.waitForURL(`${origin}/prototype`);
 assert.equal(new URL(page.url()).pathname,'/prototype');
 await page.getByRole('button',{name:'Reset data simulasi'}).click();assert.equal((await snapshot()).state.trips.length,3);
 assert.deepEqual(apiCalls,[],'Prototype must not call business APIs');assert.deepEqual(errors,[]);
 console.log('PASS: prototype routes, group payment, persistence, search, create trip, mapping, inventory lend/return, expense, CSV, attendance print (21 people), 7 mobile pages, navigation, reset. No business API calls.');
} finally {await browser.close();}
